// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Core__Int from "@rescript/core/src/Core__Int.js";
import * as Core__Array from "@rescript/core/src/Core__Array.js";

var text = Fs.readFileSync("../input/day1.txt", "utf-8");

function getNumbers(input) {
  if (input.length === 0) {
    return 0;
  }
  var numbers = input.split("").filter(function (value) {
        return Core__Int.fromString(undefined, value) !== undefined;
      });
  var value = numbers[0];
  var part1 = value !== undefined ? value : "";
  var value$1 = numbers[numbers.length - 1 | 0];
  var part2 = value$1 !== undefined ? value$1 : "";
  var sum = part1 + part2;
  var value$2 = Core__Int.fromString(undefined, sum);
  if (value$2 !== undefined) {
    return value$2;
  } else {
    return 0;
  }
}

var sum = Core__Array.reduce(text.split("\n"), 0, (function (prev, current) {
        return prev + getNumbers(current) | 0;
      }));

console.log(sum);

export {
  text ,
  getNumbers ,
  sum ,
}
/* text Not a pure module */
