// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";

var text = Fs.readFileSync("../input/day1.txt", "utf-8");

function getNumbers(input) {
  if (input.length === 0) {
    return 0;
  }
  var numbers = input.split("").filter(function (value) {
        return !Number.isNaN(Number(value));
      });
  var value = numbers[0];
  var part1 = value !== undefined ? value : "";
  var value$1 = numbers[numbers.length - 1 | 0];
  var part2 = value$1 !== undefined ? value$1 : "";
  var sum = part1 + part2;
  var value$2 = Belt_Int.fromString(sum);
  if (value$2 !== undefined) {
    return value$2;
  } else {
    return 0;
  }
}

var sum = text.split("\n").reduce((function (prev, current) {
        return prev + getNumbers(current) | 0;
      }), 0);

console.log(sum);

export {
  text ,
  getNumbers ,
  sum ,
}
/* text Not a pure module */
